### PR TITLE
updating email template again

### PR DESCRIPTION
**Pull request by jchapin**
@cbradshaw I'm not sure if the branch has all of your updates.

### CODE REVIEW

**Comment by cbradshaw** [comment]
This was my second attempt. The first commit wouldn't allow me to make a PR perhaps because my git identity was off or maybe it did go to the harrys master project. I simply removed a few blank lines at the bottom to get it to register for a new commit.

**Comment by cbradshaw** [comment]
actually that first commit is here: https://github.com/capitaltechnologyservices/prelaunchr_for_ni/commit/43dbf108ae4a290266ce40e5803cef624331dc0c

**Comment by jchapin** [comment]
We may already have the changes in there... odd:

```
You are currently cherry-picking commit 43dbf10.

nothing to commit, working directory clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
```

**Comment by jchapin** [comment]
Deploying...

**Comment by jchapin** [comment]
```
remote: -----> Compressing...
remote:        Done: 40.1M
remote: -----> Launching...
remote:        Released v32
remote:        https://ni-prelaunchr-dev.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/ni-prelaunchr-dev.git
```

**Comment by jchapin** [comment]
App is throwing an exception now.

screen shot 2016-02-25 at 3 06 43 pm

**Pull request merged**
